#stage 0

FROM tiangolo/node-frontend:10 as build-stage

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY ./ /app/

RUN npm run build

#stage 1

FROM nginx:1.15

COPY --from=build-stage /app/ /usr/share/nginx/html